# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++14 -Wall -Wextra

# Target names
OBJ = BigInteger.o
DEMO_EXE = demo.exe
TEST_EXE = test.exe

$(OBJ): BigInteger.h BigInteger.cpp
	$(CXX) $(CXXFLAGS) -c BigInteger.cpp -o $(OBJ)

demo: $(OBJ) demo.cpp
	$(CXX) $(CXXFLAGS) -o $(DEMO_EXE) demo.cpp $(OBJ)

run_demo: demo
	./$(DEMO_EXE)

test: $(OBJ) test.cpp
	$(CXX) $(CXXFLAGS) -o $(TEST_EXE) test.cpp $(OBJ)

run_test: test
	./$(TEST_EXE)

clean:
	rm -f *.o *.exe log.txt Collatz_Conjecture.txt

rebuild: clean demo test
